// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBterfnbxRc39jOIikw5RIO_3dRDUEaZ18',
    appId: '1:212518069814:web:a0a0c82df5ddd2f3735a97',
    messagingSenderId: '212518069814',
    projectId: 'adminshop-8f22f',
    authDomain: 'adminshop-8f22f.firebaseapp.com',
    storageBucket: 'adminshop-8f22f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-xiyARIzbvU8_73VZv49W9LSdG7SQE8',
    appId: '1:212518069814:android:9fe70cb42a43ab76735a97',
    messagingSenderId: '212518069814',
    projectId: 'adminshop-8f22f',
    storageBucket: 'adminshop-8f22f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuQPKxytpaPaQ9Z-OVRj-Zk8WgkYPb7SY',
    appId: '1:212518069814:ios:0fa08995621b4cfd735a97',
    messagingSenderId: '212518069814',
    projectId: 'adminshop-8f22f',
    storageBucket: 'adminshop-8f22f.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuQPKxytpaPaQ9Z-OVRj-Zk8WgkYPb7SY',
    appId: '1:212518069814:ios:d074470683be4f19735a97',
    messagingSenderId: '212518069814',
    projectId: 'adminshop-8f22f',
    storageBucket: 'adminshop-8f22f.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );
}
